CREATE TYPE "ProblemType" AS ENUM ('STANDARD', 'SCORING', 'INTERACTIVE');
CREATE TYPE "ScoringMode" AS ENUM ('TARGET', 'MAXIMIZE', 'MINIMIZE');

ALTER TABLE "problems"
  ADD COLUMN "problemType" "ProblemType" NOT NULL DEFAULT 'STANDARD',
  ADD COLUMN "scoringMode" "ScoringMode" NOT NULL DEFAULT 'TARGET',
  ADD COLUMN "maxScore" DOUBLE PRECISION NOT NULL DEFAULT 100,
  ADD COLUMN "isPractice" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "compileOptions" JSONB NOT NULL DEFAULT '{}';

ALTER TABLE "submissions"
  ADD COLUMN "score" DOUBLE PRECISION;

ALTER TABLE "submission_test_results"
  ADD COLUMN "score" DOUBLE PRECISION;
