import type { Language } from '../api/types';

export const LANGUAGE_OPTIONS: { value: Language; label: string }[] = [
  { value: 'CPP', label: 'C++17' },
  { value: 'C', label: 'C' },
  { value: 'JAVA', label: 'Java (class Main)' },
  { value: 'PYTHON3', label: 'Python 3' },
  { value: 'JAVASCRIPT', label: 'Node.js' },
  { value: 'GO', label: 'Go' },
  { value: 'CSHARP', label: 'C#' },
  { value: 'KOTLIN', label: 'Kotlin' },
  { value: 'SWIFT', label: 'Swift' },
  { value: 'RUBY', label: 'Ruby' },
  { value: 'RUST', label: 'Rust' },
  { value: 'PHP', label: 'PHP' },
  { value: 'LUA', label: 'Lua' },
  { value: 'PERL', label: 'Perl' },
  { value: 'HASKELL', label: 'Haskell' },
  { value: 'R', label: 'R' },
  { value: 'DART', label: 'Dart' },
  { value: 'BASH', label: 'Bash' },
  { value: 'JULIA', label: 'Julia' },
  { value: 'NIM', label: 'Nim' },
  { value: 'CRYSTAL', label: 'Crystal' },
  { value: 'PASCAL', label: 'Pascal' },
  { value: 'TEXT', label: '텍스트' },
];

export const DEFAULT_TEMPLATE: Record<Language, string> = {
  CPP: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    \n    return 0;\n}\n',
  C: '#include <stdio.h>\n\nint main(void) {\n    \n    return 0;\n}\n',
  JAVA: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        \n    }\n}\n',
  PYTHON3: 'import sys\n\ndef main():\n    pass\n\nif __name__ == "__main__":\n    main()\n',
  JAVASCRIPT:
    'const lines = require("fs").readFileSync("/dev/stdin", "utf8").split("\\n");\n\n// TODO\n',
  GO: 'package main\n\nimport "fmt"\n\nfunc main() {\n\n}\n',
  CSHARP:
    'using System;\n\nclass Program {\n    static void Main(string[] args) {\n        \n    }\n}\n',
  KOTLIN: 'fun main() {\n    \n}\n',
  SWIFT: 'import Foundation\n\n',
  RUBY: '',
  RUST: 'fn main() {\n    \n}\n',
  PHP: '<?php\n\n',
  LUA: '',
  PERL: 'use strict;\nuse warnings;\n\n',
  HASKELL: 'main :: IO ()\nmain = do\n    return ()\n',
  R: '',
  DART: 'void main() {\n  \n}\n',
  BASH: '#!/bin/bash\n\n',
  JULIA: '',
  NIM: '',
  CRYSTAL: '',
  PASCAL: 'program Main;\nbegin\n  \nend.\n',
  TEXT: '',
};
